### ISSUE TITLE
Ensure that there is only one instance of "graphql" in the node_modules
directory

### ISSUE THREAD

**Issue by peterschussheim** [graphql-boilerplates/typescript-graphql-server#136]
## Problem

Setting up a new server using `advanced` TS example (via `prisma` cli) throws the following error:

```bash
Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/jsutils/instanceOf.js:17:13)
    at isSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/schema.js:48:35)
    at validateSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/validate.js:51:25)
    at assertValidSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/validate.js:76:16)
    at Object.validate (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/validation/validate.js:61:35)
    at doRunQuery (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/apollo-server-core/src/runQuery.ts:143:30)
    at /Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/apollo-server-core/src/runQuery.ts:69:39
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Workaround

As per the following [suggestion](https://yarnpkg.com/en/docs/selective-version-resolutions), adding a `resolutions` key to the `package.json` of the newly initialized project fixes the issue:

```json
"resolutions": {
    "graphql": "^0.13.0"
  }
```

## Related

- [graphcool/prisma#1928](https://github.com/graphcool/prisma/issues/1928)

**Comment by moritzmorgenroth** [comment]
The workaround works locally, however does not appear to work when deploying to now.

**Comment by marktani** [comment]
Hey @peterschussheim and @moritzmorgenroth, thanks for chiming in here! Could you please try the steps outlined [in this comment](https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-367368045)? Let me know if that doesn't fix the problem for you 🙂

**Comment by marktani** [comment]
This should be resolved by now 🙂
