### ISSUE TITLE
Yarn start command failing on dotenv with a fresh install

### ISSUE THREAD

**Issue by jonlambert** [graphql-boilerplates/typescript-graphql-server#263]
Just installed a fresh version of the 'TypeScript Advanced' boilerplate via the `graphql create` command. When running `yarn start`, it fails with the following:

```
➜  server yarn start
yarn run v1.6.0
warning package.json: No license field
$ dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts
/usr/local/lib/ruby/gems/2.3.0/gems/dotenv-2.4.0/lib/dotenv/cli.rb:20:in `exec': No such file or directory - -- (Errno::ENOENT)
        from /usr/local/lib/ruby/gems/2.3.0/gems/dotenv-2.4.0/lib/dotenv/cli.rb:20:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/dotenv-2.4.0/bin/dotenv:4:in `<top (required)>'
        from /usr/local/bin/dotenv:23:in `load'
        from /usr/local/bin/dotenv:23:in `<main>'
```

**Comment by jonlambert** [comment]
Please ignore this - yarn workspaces-related dependancy issue. Working fine!

**Comment by marktani** [comment]
Thanks for the clarification, @jonlambert :+1:
